### ISSUE TITLE
Play beat

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#1]
As a user 
I want to have a prominent playbutton
so that i can play a beat.

![Image](https://user-images.githubusercontent.com/107583280/190602379-70cab174-4cc6-41bc-973a-257eddce6325.png)

## Acceptance criteria (ac)

- [ ]  there is a button on the page
- [ ]  when the button is clicked,  then a beat plays
- [ ]  the button is big and in the center of the page

## tasks

- [ ]  create a branch
- [ ]  create a button
- [ ]  create a icon
- [ ]  position the button on the page
- [ ]  add event listener to button to play a beat on click
- [ ]  add mp3 files
