### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#11]
As a user
I want to delete recorded tracks,
So I can remove the ones I don't like anymore

![Image](https://user-images.githubusercontent.com/107583280/190865442-29c2942b-36c8-4ba4-bbcf-4975d935b8a9.png)

## Acceptance criteria (ac)

- [ ] there is a button 
- [ ] when the button is clicked, the file will be deleted
- [ ] the button is left from the progress bar

## tasks

- [ ] create a button
- [ ] position the button on the page
- [ ] add event listener to delete the file
