### ISSUE TITLE
tape (lottiefile)

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#16]
As a user
I want to have my player details in the tape,
So that my recordings appear more authentic.

![Image](https://user-images.githubusercontent.com/107583280/191832699-0227eddb-ad23-4ec0-82dc-83e121c4a172.png)

## Acceptance criteria (ac)

- [ ] there is lottifile
- [ ] from now on the player-details are in the tape

## tasks

- [ ] create a new branch
- [ ] insert a lottifile 
- [ ] style the buttons 
- [ ] put the producer description in the lottifile description-field
