### ISSUE TITLE
tape animation

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#17]
As a user
I want that the tape wheels to spin, when I click the play button for the beats
so that i know that the player is active

![Image](https://user-images.githubusercontent.com/107583280/191834989-6cf4b5e3-8b5e-4743-9cd2-0da440b4089b.png)

## Acceptance criteria (ac)

- [ ] the play button and the wheels are connected
- [ ] when the play button is clicked, then the wheels turn

## tasks

- [ ] add event listener to playbutton to spin the wheels on click
