### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#20]
As a user
I want to have a landing page
So that I know what to expect.

![Image](https://user-images.githubusercontent.com/107583280/192879430-b33db111-afc5-4d1d-a56c-d7274045a0f3.png)

## Acceptance criteria (ac)

- [ ] there are a introduction with an parallax effect
- [ ] when the display is scroll, the next step is displayed
- [ ] there is a button on the page
- [ ] when the start button is clicked, you get to the main page 

## tasks

- [ ]  create a branch
- [ ]  create a button
- [ ]  install react-spring (for the parrallax effects)
- [ ]  position the button on the page

**Comment by mbosselmann** [comment]
Hi Omer,
I like your user story! I only have one typo: there **is an** introduction with a slide effect and not **are a** introduction with a slide effect. Only nit-picking. ;)
Happy hacking! 💪

**Comment by OmerAdam34** [comment]
Hi Mareike, thanks for the feedback. I've changed my mind :D 
So I updated my user story again. Please let me know if something is missing

**Comment by mbosselmann** [comment]
Hi Omer,
I just researched about the parallax effect and I'm looking forward to your implementation. :D
The user story is good! 👍 But the typo is not gone yet. ;)
Happy hacking! 🎶
