### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#21]
As a user 
I want the player controls in the tape/cassette
so that it looks like a player

![Image](https://user-images.githubusercontent.com/107583280/192873857-919f3e03-efdb-477f-a9f6-307b42a865e4.png)

## Acceptance criteria (ac)

- [ ] create buttons
- [ ] put matching icons in the buttons
- [ ] the buttons are in the box/cassette

## tasks

- [ ] create components with styled-components for the buttons
- [ ] match the buttons to the shape of cassette (see sketch )
