### ISSUE TITLE
background video

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#22]
As a user 
I want to have a background video on the landing page
so that I feel like making music

![Image](https://user-images.githubusercontent.com/107583280/192869807-8f32e09f-ba07-4a2a-9e7f-accd3a4e8b12.png)

## Acceptance criteria (ac)

- [ ] there is a background-video on the landing page
- [ ] when the first short video ends, the next one starts right away

## Task

- [ ] put videos in the code
- [ ] make it autoplay and give them a loop
- [ ] style the start button 
- [ ] give the introduction a new font and size
