### ISSUE TITLE
sign in with github

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#23]
As a user
I want to sign in with my github profile
so that I have my own space in the app

![Image](https://user-images.githubusercontent.com/107583280/193006548-d495656d-59e1-4c30-81cc-c6f707b5cf10.png)

- [ ] there is a headline -> "Sign in"
- [ ] there is a button in the center of the landing page
- [ ] when the sign in button is clicked, he is logged in
- [ ] after logging in, the user is forwarded to the introduction page. with a greeting "Hello -User-"

## tasks

- [ ] create a branch
- [ ] create a button with the github icon
- [ ] position the button on the page
- [ ] integrate useSession, signIn and signOut
- [ ] forwarding to the introduction page
