### ISSUE TITLE
sign in with google

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#24]
As a user
I want to sign in with my google profile
so that I have my own space in the app

![Image](https://user-images.githubusercontent.com/107583280/193006455-db1116c0-b893-44e6-9a81-ee04144bafa8.png)

- [ ] there is a button below the github button
- [ ] when the sign in button is clicked, he is logged in
- [ ] after logging in, the user is forwarded to the introduction page. with a greeting "Hello -User-"

## tasks

- [ ] create a branch
- [ ] create a button with the google icon
- [ ] position the button on the page
- [ ] forwarding to the introduction page
