### ISSUE TITLE
Stop the beat

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#3]
As a user 
I want to stop the beat,
so that i can focus on something else

![Image](https://user-images.githubusercontent.com/107583280/190633648-047d8fa0-ba04-421b-bbf5-365cffb4b385.png)

## Acceptance criteria (ac)

- [ ] the pause button is integrated in the play button
- [ ] when the button is clicked, then a beat stops
- [ ] when the button is clicked again, than the beat will continue

## tasks

- [ ] creat a icon (pause)
- [ ] add event listener to button to pause a beat on click
