### ISSUE TITLE
Skip beats/loops

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#4]
As a user
I want to skip tracks,
So that I have more beats options.

![Image](https://user-images.githubusercontent.com/107583280/190640111-348d159d-e853-4b36-8f65-d9a7f6304bff.png)

## Acceptance criteria (ac)

- [ ] there are two buttons on the page - (forward, backward)
- [ ] when one of the button is clicked, then a new beat/loop plays
- [ ] the forward button is to the right of the play button
- [ ] the backward button is to the left of the play button

## tasks

- [ ] create two buttons
- [ ] create two icons
- [ ] position the buttons on the page
- [ ] add even listener to buttons to skip a beat on click
- [ ] ad more mp3 files

**Comment by K-Juno** [comment]
Hi Omar, really excited about your capstone project!
Do you already have mp3 files at this point, which your buttons can work with?

**Comment by OmerAdam34** [comment]
Hi Juni, thank you for your comment. 
Sure, in the first step I will put a mp3 file. 
In this part I´ll put more beats/loops in my app, for the skip function.
:)
