### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#5]
As a user
I want to record my lyrics,
So that I improve my rap skills

![Image](https://user-images.githubusercontent.com/107583280/190658354-955fde48-9b59-4e48-9292-68584d449981.png)

## Acceptance criteria (ac)

- [ ] there is a button to left of the skip button
- [ ] when the button is clicked, it will be recorded your voice

## Task

- [ ] create a button
- [ ] create a icon
- [ ] position the button on the page
- [ ] add event listener to button to record your voice

**Comment by DoroVernier** [comment]
Hi Omer, that looks all pretty cool! My thumpsUp!!!
