### ISSUE TITLE
save beat and voice

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#6]
As a user
I want to save my tracks,
So that I can play my own song again

![Image](https://user-images.githubusercontent.com/107583280/190718576-aee43a0d-89fc-44bf-8f0e-a737540dc120.png)

## Acceptance criteria (ac)

- [ ] there is a progress bar
- [ ] when the rap/lyric and the beat/loop stops, then the progress bar is displayed
- [ ] the bar is under the player/skip etc buttons

## tasks

- [ ] create a button and a range
- [ ] create a icon for the play button
- [ ] the recording is saved and displayed

**Comment by AnH13-6** [comment]
Hey ho! 
Stimmt es, dass die progress bar nur erscheint, wenn der beat stoppt? So klingt es in Punkt 2 der ac, aber die müsste immer angezeigt werden, oder?
Ich verstehe auch nicht ganz, wie die progress bar beim speichern der songs hilft. Laut deiner User Story ist das doch der Punkt, um den es hier gehen soll, oder? Mir fehlt ein Button, der  den Track speichern kann in deiner Zeichnung. 
Ich würde zwei verschiedene issues machen, eins für die Progressbar und dann ein zweites fürs Speichern der Tracks.

Falls ich das alles nur nicht verstanden hab, klär mich auf 😄

**Comment by OmerAdam34** [comment]
Hi, danke für dein Feedback :) 
Genau, die Progressbar wird ausgespuckt, nachdem fertig  aufgenommen wurde - daher ein zusätzliches Feature zum Player.  Die Datei mit der progressbar wird dann erstmal lokal gespeichert. 
In der nächsten User Story kommt es zum Download, damit die Datei auch auf devices herunter runtergeladen werden können. 
Gib mir gerne nochmal Rückmeldung, ob die Funktion so Sinn ergibt 🙈

**Comment by AnH13-6** [comment]
Wäre eine Progressbar nicht auch hilfreich beim Aufnehmen? Aber ich kenn mich mit sowas nicht aus ... 😅 Und mir fehlt da irgendwie wirklich ein Button zum Speichern, aber vielleicht fehlt mir auch einfach die Vorstellungskraft, wie es nachher alles funktionieren und aussehen soll

**Comment by OmerAdam34** [comment]
Ahhh nun verstehe ich. In dieser user story geht es tatsächlich nur um die Ausgabe des tracks. Immer nach ende der Aufnahme, wir die Datei mit einer  Progressbar ausgegeben. 

Da das Feature mit dem Download doch etwas aufwendiger ist als zuvor angenommen, habe ich das ausgeben als auch downloaden voneinander  getrennt (siehe nächste user Story.)
