### ISSUE TITLE
download file

### ISSUE THREAD

**Issue by OmerAdam34** [OmerAdam34/capstone-project#7]
As a user
I want to download my track,
So that I can listen it on my devices.

![11](https://user-images.githubusercontent.com/107583280/190862627-e74f6bbf-0143-4ff5-a019-43aa9572d536.png)

## Acceptance criteria (ac)

- [ ] there is a button 
- [ ] when the file button is clicked, the recording will be saved to the device in a list.
- [ ] the button is right from the progress bar

## tasks

- [ ] create a button
- [ ] create a icon
- [ ] create a list
- [ ] position the button on the page
- [ ] add event listener to to save the file on the device

**Comment by AnH13-6** [comment]
Hey hey. 
Maybe it would make more sense to have a list of my tracks and download them from there? 
Do you save them locally first as it sounded in issue 6 with the save button you wanted to add there? I can't see a button like that in this drawing. Also, how would a user know if a track has already been saved, when the view is still the same as on the recording page?
In the ac, you wrote that the button is left of the progress bar, but in the picture it's on the right.
(sorry for all these questions, I hope it's not too much!)

**Comment by OmerAdam34** [comment]
Hi :) Thanks for your reply. Ah thats a good idea with the list. I will definitely change that and try to implement it.
In fact, I was wrong about the button. I'll adjust that too.

super helpful thoughts :)

**Comment by AnH13-6** [comment]
One thing I just thought of: Maybe you could also give each recorded trach an indivudual title, so that the user knows which one is which. Otherwise it looks very nice!
